use ecommerce_analytics;
/*
============================================================
10 - JOINS | NORTHWIND SQL PROJECT
============================================================
COMMON RELATIONSHIPS
--------------------
orders.customerID        → customers.customerID
orders.employeeID        → employees.employeeID
orders.orderID           → order_details.orderID
order_details.productID  → products.productID
products.categoryID      → categories.categoryID
orders.shipVia           → shippers.shipperID
employees.reportsTo      → employees.employeeID

============================================================*/


/*==========================================================
1. INNER JOIN
Use when you need ONLY matching records from both tables.
==========================================================*/

-- Question:
-- Show orders with customer names.
SELECT 
 o.orderID,
 c.customerID,
 c.companyName,
 o.orderDate
FROM orders o
INNER JOIN customers c
ON o.customerID=c.customerID;


/*==========================================================
2. INNER JOIN + MULTIPLE TABLES
==========================================================*/

-- Question:
-- Show order, customer and employee information.
SELECT 
 o.orderID,
 p.productID,
 p.productName,
 c.customerID,
 c.companyName,
 e.employeeID,
 CONCAT(e.firstName,' ',e.lastName) AS EmpName
FROM orders o
INNER JOIN customers c
ON o.customerID=c.customerID
INNER JOIN employees e
ON o.employeeID=e.employeeID
INNER JOIN order_details od
ON o.orderID=od.orderID
INNER JOIN products p
on od.productID=p.productID;


/*==========================================================
3. INNER JOIN — ORDER DETAILS + PRODUCTS
==========================================================*/
-- Question:
-- Show products included in each order.
SELECT
 o.orderID,
 p.productID,
 p.productName,
 p.unitPrice,
 o.quantity
FROM order_details o
JOIN products p
ON o.productID=p.productID;
 

/*==========================================================
4. LEFT JOIN
Keep ALL records from the LEFT table.
==========================================================*/

-- Question:
-- Show all customers, including customers with no orders.
SELECT 
 c.customerID,
 c.companyName,
 o.orderID
FROM customers c
LEFT JOIN orders o
ON c.customerID=o.orderID;

/*==========================================================
5. LEFT JOIN + IS NULL
Find records with NO MATCH.
==========================================================*/

-- Question:
-- Which customers have never placed an order?
SELECT 
 c.customerID,
 c.companyName,
 o.orderID
FROM customers c
LEFT JOIN orders o
ON c.customerID=o.orderID
WHERE o.orderID IS NULL;


/*==========================================================
6. RIGHT JOIN
Keep ALL records from the RIGHT table.
==========================================================*/

-- Question:
-- Show every order with its customer.
SELECT 
 o.orderID,
 c.companyName AS customerName,
 p.productName
FROM customers c
RIGHT JOIN orders o
ON c.customerID=o.customerID
JOIN order_details od
ON o.orderID=od.orderID
RIGHT JOIN products p
ON od.productID=p.productID;


/*==========================================================
8. CROSS JOIN
Every possible combination of rows.
No ON condition.
==========================================================*/

-- Question:
-- Generate every category × shipper combination.

SELECT
    c.categoryName,
    s.companyName AS shipper
FROM categories c
CROSS JOIN shippers s;


/*==========================================================
9. MULTI-TABLE JOIN
==========================================================*/

-- Question:
-- Show order + customer + product + category.




/*==========================================================
10. JOIN + CALCULATION
==========================================================*/

-- Question:
-- Calculate revenue for every product sold.

-- Revenue Formula:
-- unitPrice × quantity × (1 - discount)




/*==========================================================
11. JOIN + WHERE
==========================================================*/

-- Question:
-- Show orders placed by customers from Germany.
SELECT 
 o.orderID,
 c.customerID,
 c.companyName AS customerName,
 c.country
FROM customers c
INNER JOIN orders o
ON c.customerID=o.customerID
WHERE c.country='Germany';
 


/*==========================================================
12. JOIN + GROUP BY
==========================================================*/

-- Question:
-- Find total revenue generated by each customer.

SELECT 
 c.customerID,
 c.companyName AS customerName,
 SUM(od.unitPrice*od.quantity*(1-od.discount)) AS total_revenue
FROM customers c
JOIN orders o
ON c.customerID=o.customerID
JOIN order_details od
ON o.orderID=od.orderID
GROUP BY c.customerID,c.companyName;

