use ecommerce_analytics;
/*
====================================================
11 - SUBQUERIES
====================================================
*/


-- Products above average price
SELECT 
productID,
productName,
unitPrice
FROM products
WHERE unitPrice >(
SELECT AVG(unitPrice) 
FROM products
);

-- 2. Products at maximum price
SELECT 
productID,
productName,
unitPrice
FROM products
WHERE unitPrice =
(
SELECT 
MAX(unitPrice) FROM products
);

-- 3. IN
-- Customers who placed orders
SELECT 
customerID,
companyName AS customerName
FROM customers
WHERE customerID IN (
SELECT customerID
FROM orders
);
-- 4. NOT IN
-- Customers without orders
SELECT 
customerID,
companyName AS customerName
FROM customers
WHERE customerID NOT IN (
SELECT customerID
FROM orders
);

-- 5. EXISTS
-- Find customers who have placed at least one order.
SELECT 
c.customerID,
c.companyName AS customerName
FROM customers c
WHERE EXISTS (
SELECT 1
FROM orders o 
WHERE o.customerID=c.customerID
);
-- 6. NOT EXISTS
SELECT 
c.customerID,
c.companyName AS customerName
FROM customers c
WHERE NOT EXISTS (
SELECT 1
FROM orders o 
WHERE o.customerID=c.customerID
);

-- 7. Subquery in FROM
-- Calculate the total revenue generated by each product.
SELECT 
 productID,
 productName,
 Revenue
 FROM (
 SELECT 
 o.productID,
 p.productName,
  SUM(o.unitPrice*o.quantity*(1-o.discount)) AS Revenue 
  FROM order_details o
  JOIN products p
  ON o.productID=p.productID
  GROUP BY o.productID,p.productName 
  ORDER BY o.productID) 
  AS product_sales;
  
-- 8. Subquery in SELECT
-- Show every product's price along with the overall average product price.
SELECT 
 p.productID,
 p.productName,
 p.unitPrice,
 (
  SELECT 
   AVG(unitPrice) AS Average_Price
   FROM products
 ) AS average_price
 FROM products p;
 
-- 9. Correlated subquery
-- Find products whose price is higher than the average price of products in their own category.
SELECT 
p.productID,
p.productName,
p.unitPrice,
p.categoryID
FROM products p
WHERE p.unitPrice >
(
 SELECT
 AVG(p2.unitPrice)
 FROM products p2
 WHERE p2.categoryID=p.categoryID
);

-- 10. Customers with above-average order count
SELECT
    c.customerID,
    c.companyName AS customerName,
    COUNT(*) AS order_count
FROM orders o
JOIN customers c
ON o.customerID=c.customerID
GROUP BY c.customerID,c.companyName
HAVING COUNT(*) > (
    SELECT AVG(order_count)
    FROM (
        SELECT
            customerID,
            COUNT(*) AS order_count
        FROM orders
        GROUP BY customerID
    ) AS customer_orders
);
